project:
  type: book
  output-dir: _book

book:
  title: "Pharmacokinetics/Pharmacodynamics Modelling"
  author: "Matthias König"
  date: "4/7/2025"
  chapters:
    - index.qmd
    - concept.qmd
    - content.qmd
    - install.qmd
    - mu.qmd
    - notebooks/hello.ipynb

bibliography: references.json

format:
  html:
    theme: cosmo
    cover-image: images/banner.png
#   pdf:
#    documentclass: scrreprt
#    cover-image: images/banner.png
#  epub:
#    cover-image: images/banner.png