project:
  type: book
  output-dir: _book

# number-depth: 0

book:
  title: "Pharmacokinetic & pharmacodynamic modelling"
  author: "Matthias König"
  date: "4/9/2025"
  chapters:
    - index.qmd
    - part: "Concept"
      chapters:
      - course_concept.qmd
    - part: "Course"
      chapters:
      - course_overview.qmd
      # - lecture_pkparameters.qmd
      - ./notebooks/course/01_structural_models.ipynb
      - ./notebooks/course/02_ordinary_differential_equations.ipynb
      - ./notebooks/course/03_compartment_model.ipynb
      - ./notebooks/course/04_absorption.ipynb
      - ./notebooks/course/05_multiple_dosing.ipynb
      - ./notebooks/course/06_metabolism.ipynb
      - ./notebooks/course/07_pharmacokinetic_parameters.ipynb
      - ./notebooks/course/08_variability.ipynb
      - ./notebooks/course/09_sbml.ipynb
      - ./notebooks/course/10_pharmacodynamics.ipynb
      - ./notebooks/course/11_pbpk_tutorial.ipynb

    - part: "Technology"
      chapters:
      - install.qmd
      - technology_review.qmd
    - part: "TODO"
      chapters:
      - todo.qmd
  favicon: ./images/pkpd.png
  twitter-card: true
  repo-url: https://github.com/matthiaskoenig/dhpe-pkpd.git
  site-url: https://livermetabolism.com
  downloads: [pdf]
  
  # navbar:
  #   background: primary
  #   search: false
  #   title: PK/PD modelling


  sidebar:
    contents: auto
    style: "floating"
    logo: ./images/pkpd.png
    collapse-level: 3
    search: true

# comments:
#  hypothesis: true

bibliography: references.json

format:
  html:
    theme: cosmo
    # cover-image: images/banner.png
  # pdf:
  #   documentclass: scrreprt
  #   cover-image: images/banner.png
  # typst:
  #   default
  # epub:
  #   default
    # cover-image: images/banner.png