project:
  type: book
  output-dir: _book

book:
  title: "Pharmacokinetics/Pharmacodynamics Modelling"
  author: "Matthias König"
  date: "4/7/2025"
  chapters:
    - index.qmd
    - course_content.qmd
    - teaching_concept.qmd
    - install.qmd

bibliography: references.json

format:
  html:
    theme: cosmo
    # cover-image: images/banner.png
#   pdf:
#    documentclass: scrreprt
#    cover-image: images/banner.png
#  epub:
#    cover-image: images/banner.png